### PR TITLE
build(deps): esy-cmake->@revery/esy-cmake@0.3.5001

### PR DESCRIPTION
**Pull request by Et7f3**

### CODE REVIEW

**Comment by zbaylin** [comment]
Hmm on macOS I now get the error
```
In file included from /Users/zbaylin/Development/esy-astyle/mac/src/ASBeautifier.cpp:10:
In file included from /Users/zbaylin/Development/esy-astyle/mac/src/astyle.h:17:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cassert:20:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/astyle.dir/src/ASBeautifier.cpp.o] Error 1
make[1]: *** [CMakeFiles/astyle.dir/all] Error 2
make: *** [all] Error 2
error: command failed: 'bash' './esy/build.sh' (exited with 2)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1
```
Unclear if that's related to the cmake change, though

**Comment by Et7f3** [comment]
Can you test on master ? Because it works in revery-ci.

**Comment by zbaylin** [comment]
You're right, something got messed up on master. Strange -- it builds fine in revery locally.

**Comment by Et7f3** [comment]
master of revery or esy-astyle ? Have you a issue in building https://github.com/revery-ui/revery/tree/reduce-deps (we should obtain after merge)

**Comment by zbaylin** [comment]
I should probably set up some CI for this. I can also transfer ownership to the Revery org if @bryphe thinks that would be a good idea and we could use the Azure pipelines setup there. But yeah I have no problem merging this in.

**Comment by zbaylin** [comment]
I added a very basic CI implementation in #2, once that gets merged I'll merge up master here and if it passes I'll merge this 👍

**Pull request merged**
